### ISSUE TITLE
Depth Anything support

### ISSUE THREAD

**Issue by ThreeDeeJay** [parkchamchi/DepthViewer#14]
As mentioned in https://github.com/parkchamchi/DepthViewer/issues/9#issuecomment-1903546025, there's [this new model](https://github.com/LiheYoung/Depth-Anything) that's been making the rounds and it's indeed [comparable](https://airtable.com/appjWiS91OlaXXtf0/shrlyfglV34siHrqt) to [BEiT](https://imgsli.com/MjM0ODc0/2/3) in terms of detection accuracy, though I'm curious about performance, so I just tried loading the [third-party ONNX version](https://github.com/fabio-sim/Depth-Anything-ONNX/releases/latest) via the Unity app, but I'm getting the following errors:

This part repeats for infinitely/every frame when attempting to play a video file. happens with all models, whether GPU/CUDA is enabled or not
```python
RenderTexture.Create failed: width & height must be larger than 0
Texture has out of range width / height
UnityException: Failed to create texture because of invalid parameters.
UnityEngine.Texture2D.Internal_Create (UnityEngine.Texture2D mono, System.Int32 w, System.Int32 h, System.Int32 mipCount, UnityEngine.Experimental.Rendering.GraphicsFormat format, UnityEngine.Experimental.Rendering.TextureCreationFlags flags, System.IntPtr nativeTex) (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
UnityEngine.Texture2D..ctor (System.Int32 width, System.Int32 height, UnityEngine.TextureFormat textureFormat, System.Int32 mipCount, System.Boolean linear, System.IntPtr nativeTex) (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
UnityEngine.Texture2D..ctor (System.Int32 width, System.Int32 height) (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
OnnxRuntimeDepthModel.Run (UnityEngine.Texture inputTexture) (at <c22d50f66c014b868279a538562184fd>:0)
ImgVidDepthTexInputs.UpdateVid () (at <c22d50f66c014b868279a538562184fd>:0)
ImgVidDepthTexInputs.UpdateTex () (at <c22d50f66c014b868279a538562184fd>:0)
MainBehavior.Update () (at <c22d50f66c014b868279a538562184fd>:0)
```

The error is different when loading images though:

```python
RenderTexture.Create failed: width & height must be larger than 0
Texture has out of range width / height
UnityException: Failed to create texture because of invalid parameters.
UnityEngine.Texture2D.Internal_Create (UnityEngine.Texture2D mono, System.Int32 w, System.Int32 h, System.Int32 mipCount, UnityEngine.Experimental.Rendering.GraphicsFormat format, UnityEngine.Experimental.Rendering.TextureCreationFlags flags, System.IntPtr nativeTex) (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
UnityEngine.Texture2D..ctor (System.Int32 width, System.Int32 height, UnityEngine.TextureFormat textureFormat, System.Int32 mipCount, System.Boolean linear, System.IntPtr nativeTex) (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
UnityEngine.Texture2D..ctor (System.Int32 width, System.Int32 height) (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
OnnxRuntimeDepthModel.Run (UnityEngine.Texture inputTexture) (at <c22d50f66c014b868279a538562184fd>:0)
ImgVidDepthTexInputs.FromImage (UnityEngine.Texture texture) (at <c22d50f66c014b868279a538562184fd>:0)
ImgVidDepthTexInputs.FromImage (System.String filepath) (at <c22d50f66c014b868279a538562184fd>:0)
ImgVidDepthTexInputs..ctor (FileTypes ftype, IDepthMesh dmesh, DepthModel dmodel, System.String filepath, System.Boolean searchCache, System.Boolean canUpdateArchive, UnityEngine.Video.VideoPlayer vp, IVRRecord vrrecord, AsyncDepthModel asyncDmodel, System.Boolean forceStopNotPauseOnLoopPoints) (at <c22d50f66c014b868279a538562184fd>:0)
MainBehavior.SelectFile (System.String filepath) (at <c22d50f66c014b868279a538562184fd>:0)
MainBehavior.<BrowseFiles>b__60_0 (System.String path) (at <c22d50f66c014b868279a538562184fd>:0)
StandaloneFileSelecter.SelectFile (OnPathSelected callback) (at <c22d50f66c014b868279a538562184fd>:0)
MainBehavior.BrowseFiles () (at <c22d50f66c014b868279a538562184fd>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <e036a72b7a734c938bd0e3bb10424e1b>:0)
UnityEngine.UI.Button.Press () (at <f96b039c628241f18868828ba427ed81>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <f96b039c628241f18868828ba427ed81>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <f96b039c628241f18868828ba427ed81>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <f96b039c628241f18868828ba427ed81>:0)
UnityEngine.EventSystems.EventSystem:Update()```

**Comment by brentjohnston** [comment]
I started working on a script using some of Threedeejay's code (and need help) for the large model, right now it works with auto-creating clone to danny folder under /depthpy, downloads the dannyrunner.py, and downloads the large model and config and place in dany/checkpoints, script to be placed in main depthviewer directory. It is doing something wrong at the end though and not launching the model. (I temporily set window to not close) Needs progress bar during download indicator also. (I think I did download process this wrong also but it works)
[Depth-Anything-LargeModel.zip](https://github.com/parkchamchi/DepthViewer/files/14045048/Depth-Anything-LargeModel.zip)


```
@echo off
SetLocal EnableDelayedExpansion

REM configuration
Set "PythonVersion=3.9.6"
Set "Encoder=vitl14"
Set "DanyRunnerURL=https://raw.githubusercontent.com/parkchamchi/DepthViewer/fa2ce8398787fe4f8a7e256b958e9fd067318254/DEPTH/depthpy/danyrunner.py"
Set "RepositoryURL=https://github.com/LiheYoung/Depth-Anything"
Set "ModelURL=https://huggingface.co/LiheYoung/depth_anything_vitl14/resolve/main/pytorch_model.bin"
Set "ConfigURL=https://huggingface.co/LiheYoung/depth_anything_vitl14/resolve/main/config.json"

REM determine script directory
Set "ScriptDir=%~dp0"

REM Set the depthPy directory relative to the script directory
Set "DepthPyDirectory=%ScriptDir%depthpy"

REM set the dany clone directory within the depthPy directory
Set "CloneDirectory=%DepthPyDirectory%\dany"

REM check python version
echo Checking Python version...
for /f "tokens=2" %%P in ('python --version 2^>^&1') do (
    If "%%P"=="!PythonVersion!" (
        Echo Python !PythonVersion! detected.
    ) else (
        Echo Python !PythonVersion! not detected. Please install Python !PythonVersion!.
        Exit /B
    )
)

REM check if the dany directory already exists
echo checking if dany is already cloned...
if exist "!CloneDirectory!\.git" (
    Echo dany already cloned. Skipping clone step.
) else (
    REM clone dany
    echo cloning dany repository...
    if not exist "!CloneDirectory!" mkdir "!CloneDirectory!"
    git clone "!RepositoryURL!" "!CloneDirectory!"
    if %errorlevel% neq 0 (
        echo Failed to clone Dany repository.
        Exit /B
    )
)

REM create checkpoints folder
echo creating checkpoints folder...
if not exist "%CloneDirectory%\checkpoints" (
    mkdir "%CloneDirectory%\checkpoints"
    echo Checkpoints folder created.
) else (
    echo Checkpoints folder already exists.
)

REM download danyrunner.py
echo downloading danyrunner.py...
powershell -Command "Invoke-WebRequest -Uri '%DanyRunnerURL%' -OutFile '%DepthPyDirectory%\danyrunner.py'"
if %errorlevel% neq 0 (
    echo Failed to download danyrunner.py.
    Exit /B
) else (
    echo danyrunner.py downloaded successfully.
)

REM download model file if it does not exist
if not exist "%CloneDirectory%\checkpoints\pytorch_model.bin" (
    echo Downloading model file...
    powershell -Command "Invoke-WebRequest -Uri '%ModelURL%' -OutFile '%CloneDirectory%\checkpoints\pytorch_model.bin'"
    if %errorlevel% neq 0 (
        echo Failed to download model file.
        Exit /B
    )
) else (
    echo Model file already exists.
)

REM download config file if it does not exist
if not exist "%CloneDirectory%\checkpoints\config.json" (
    echo Downloading config file...
    powershell -Command "Invoke-WebRequest -Uri '%ConfigURL%' -OutFile '%CloneDirectory%\checkpoints\config.json'"
    if %errorlevel% neq 0 (
        echo Failed to download config file.
        Exit /B
    )
) else (
    echo Config file already exists.
)

REM navigate to depthPy Directory
echo Navigating to DepthPy Directory...
cd /d "%DepthPyDirectory%"
if %errorlevel% neq 0 (
    echo Failed to navigate to DepthPy Directory.
    Exit /B
)

REM run depth-anything model
echo Running Depth-Anything Model...
python -i danyrunner.py -r dany -t vitl14
if %errorlevel% neq 0 (
    echo failed to run depth-anything Model.
    Exit /B
) else (
    echo Depth Anything Model ran successfully.
)

echo If download failed, please place the large depth-anything model and config under %CloneDirectory%\checkpoints, download model and config here: https://huggingface.co/LiheYoung/depth_anything_vitl14/tree/main

REM prevent script from closing automatically
echo press any key to exit.
pause >nul
```

**Comment by parkchamchi** [comment]
@brentjohnston Is there any error message? The code you provide downloads the checkpoint files manually but the current `danyrunner.py` gets the pretrained model from the torchhub.

**Comment by brentjohnston** [comment]
I think I'm going to scrap mine for now because it does have and zmq or cuda code and a lot of errors, Threedeejay's almost works for me but I have this message 
![image](https://github.com/parkchamchi/DepthViewer/assets/23625562/e14d3a5d-08b0-402e-a385-11cc5921829e)

Here was the code for the initial script that sets everything up and then the depth-anything script. Is there a way to verify it does everything correctly, I don't see a reference to danyrunner.py in it and he mentions he only gets like 2 fps with depth-anyone.

Initial Evironment Setup Threedeejay Script: 
[DepthViewerLauncher.zip](https://github.com/parkchamchi/DepthViewer/files/14058883/DepthViewerLauncher.zip)

and the depth-anyone script he made: 
```
@echo off
SetLocal EnableExtensions
SetLocal EnableDelayedExpansion

Set "PythonVersion=3.9.6"
Set "TorchVersion=2.0.1+cu117"
Set "CUDA=True"
Set "CUDAVersion=11.7"

Echo DepthViewer MiDaS CUDA acceleration installer

pushd "%~dp0"

:Check
If not exist "%~dp0depthpy" (
	Echo depthpy folder not found in this location.
	Echo Please copy and run this script "%~nx0" from the folder containing depthpy, DepthViewer.exe, etc.
	Pause
	GoTo :Check
	)


:Python
Echo.
Echo Checking Python version...
for /f "tokens=2" %%P in ('python --version') do (
	If "%%P"=="!PythonVersion!" (
		Echo [92mPython !PythonVersion! detected.[0m
		) else (
		Echo [91mPython !PythonVersion! not detected.[0m
		Echo [96mPress any key to download the following file in your browser so you can install it with the following options...[0m
		Echo - Add Python !PythonVersion! to PATH
		Echo - pip
		Echo https://www.python.org/ftp/python/!PythonVersion!/python-!PythonVersion!-amd64.exe
		Pause >NUL
		Start https://www.python.org/ftp/python/!PythonVersion!/python-!PythonVersion!-amd64.exe
		Echo Press a key after Python !PythonVersion! has been installed.
		Pause >NUL
		GoTo :Python
		)
	)

:CUDA
Echo.
Echo Checking CUDA version...
for /f "tokens=1" %%C in ('python ^"%~dp0depthpy/torch.cuda.is_available.py^"') do (
	If "%%C"=="!CUDA!" (
		Echo [92mCUDA !CUDAVersion! detected.[0m
		nvcc --version
		) else (
		[91m Echo CUDA !CUDAVersion! not detected.[0m
		Echo [96mPress any key to download the following file in your browser so you can install it...[0m
		Echo https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_516.01_windows.exe
		Echo Also, you'll need to Extract and copy all the DLL files 
		Echo from cudnn-11.4-windows-x64-v8.2.4.15.zip\cuda\bin\
		Echo into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin folder
		Echo https://developer.nvidia.com/downloads/compute/cudnn/secure/8.9.3/local_installers/11.x/cudnn-windows-x86_64-8.9.3.28_cuda11-archive.zip/
		Pause >NUL
		Start https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_516.01_windows.exe
		Start https://developer.nvidia.com/downloads/compute/cudnn/secure/8.9.3/local_installers/11.x/cudnn-windows-x86_64-8.9.3.28_cuda11-archive.zip/
		Echo Press a key after CUDA and CUDNN have been installed.
		Pause >NUL
		GoTo :CUDA
		)
	)

:Torch
Echo.
Echo Checking Torch version...
for /f "tokens=*" %%T in ('python "%~dp0depthpy/torch.__version__.py"') do set "TorchVersionCheck=%%T"
If "!TorchVersionCheck!"=="!TorchVersion!" (
	Echo [92mTorch !TorchVersion! detected.[0m
	) else (
	Echo [91mTorch !TorchVersion! not detected.[0m
	Echo [96mPress any key to install it.[0m
	Pause >NUL
	pip install opencv-python
	pip install numpy
	pip uninstall -y torchvision
	pip install torchvision-0.15.2+cu117-cp39-cp39-win_amd64.whl
	pip uninstall -y torch
	pip install torch-2.0.1+cu117-cp39-cp39-win_amd64.whl
	pip uninstall -y timm
	pip install timm==0.6.13
	GoTo :Torch
	)

:Selection
CD "%~dp0depthpy\weights"
Echo.
Echo These are the models available in %~dp0depthpy\weights
Echo Please select one by typing its number then press Enter or just press Enter to cycle through all of them:
Echo 0 Marigold
Echo 1 Depth Anywhere (Large)
Echo 2 Depth Anywhere (Base)
Echo 3 Depth Anywhere (Small)
Set Model[0]=Marigold
Set Model[1]=depth_anything_vitl14
Set Model[2]=depth_anything_vitb14
Set Model[3]=depth_anything_vits14
Set ModelCount=3
For %%G IN (*.pt) do (
	Set /A ModelCount=!ModelCount!+1
	Set Model[!ModelCount!]=%%~nG
	Set Model=%%~nG
	Echo !ModelCount! %%~nG
	)
Echo Download more models from https://airtable.com/appjWiS91OlaXXtf0/shrchKmROzpsq0HFw
Set ModelCount=
SET /P ModelCount=
If Defined ModelCount (
	For %%C IN (!ModelCount!) do (
		Set Model=!Model[%%C]!
		Call :Depth %*
		)
	) else (
	For %%G IN (*.pt) do (
		Set SkipConfirmation=True
		Set Model=%%~nG
		Call :Depth %*
		)
	)
Pause
Exit

:Depth
If "!Model!"=="ZoeD_N" 						(Set ModelParameters=--frameformat pfm -r zoe)
If "!Model!"=="ZoeD_NK"						(Set ModelParameters=--frameformat pfm -r zoe)
If "!Model!"=="ZoeD_K"						(Set ModelParameters=--frameformat pfm -r zoe)
If "!Model!"=="Marigold"					(Set ModelParameters=-r mari)
If not "!Model!"=="!Model:depth_anything=!"	(Set ModelParameters=-r dany)

If "!Model!"=="Marigold"	(
	If not exist "%~dp0depthpy\Marigold\run.py" (
		Echo Marigold not found. The download should start in your browser now,
		Echo Then extract, copy "Marigold-main" renamed to "Marigold" into the depthpy folder so that run.py is located in:
		Echo "%~dp0depthpy\Marigold\run.py"
		Start https://codeload.github.com/prs-eth/Marigold/zip/refs/heads/main
		pause
		GoTo :Depth
		)
	) else (
	If not "!Model!"=="!Model:depth_anything=!"	(
		If not exist "%~dp0depthpy\dany\run.py" (
			Echo Depth Anything not found. The download should start in your browser now,
			Echo Then extract, copy "Depth-Anything-main" renamed to "dany" into the depthpy folder so that run.py is located in:
			Echo "%~dp0depthpy\dany\run.py"
			Start https://codeload.github.com/LiheYoung/Depth-Anything/zip/refs/heads/main
			pause
			GoTo :Depth
			) else (
			CD "%~dp0depthpy\dany"
			pip install -r requirements.txt
			pushd "%~dp0"
			)
		)
	)
pushd "%~dp0"
If not exist "%APPDATA%\..\LocalLow\parkchamchi\DepthViewer\depths" (MkDir "%APPDATA%\..\LocalLow\parkchamchi\DepthViewer\depths")
If "%*"=="" (
	Echo [96mWhen you see "[0mMQ: Binding to tcp://*:5556[96m", run DepthViewer.exe.[0m
	If exist "%~dp0initcmds.txt" (copy "%~dp0initcmds.txt" "%APPDATA%\..\LocalLow\parkchamchi\DepthViewer\initcmds.txt")

	CD "%~dp0depthpy"
	If "!Model!"=="Marigold" (
		@echo
		python ffpymq.py !ModelParameters! -t Bingxin/Marigold --optimize
		@echo off
		) else (
		@echo
		python ffpymq.py !ModelParameters! -t !Model:depth_anything_=! --optimize
		@echo off
		)
	pushd "%~dp0"
	) else (
	For %%F in (%*) do (
		for /f "skip=1" %%H in ('certutil -hashfile %%F SHA256') do (
			If not defined Hash (Set "Hash=%%H")
			)
		Set "OutputFileName=%%~nF%%~xF.!Model!.!Hash!.depthviewer"
		Echo.
		Echo Generating !OutputFileName!...
		If "!Model!"=="Marigold" (
			@echo
			python depthpy/depth.py --noupdate --detect_img_exts !ModelParameters! -t Bingxin/Marigold --optimize --aux_args den_s=9,ens_s=8 "%%F" "%APPDATA%\..\LocalLow\parkchamchi\DepthViewer\depths\!OutputFileName!"
			@echo off
			) else (
			@echo
			python depthpy/depth.py --noupdate --detect_img_exts !ModelParameters! -t !Model:depth_anything_=! --optimize --nostrict "%%F" "%APPDATA%\..\LocalLow\parkchamchi\DepthViewer\depths\!OutputFileName!"
			@echo off
			)
		)
	If not "!SkipConfirmation!"=="True" (
		If exist "%APPDATA%\..\LocalLow\parkchamchi\DepthViewer\depths\!OutputFileName!" (
			Echo.
			Echo Press any key to open the output folder; otherwise, you can close this window.
			Pause >NUL
			explorer.exe /select,"%APPDATA%\..\LocalLow\parkchamchi\DepthViewer\depths\!OutputFileName!"
			)
		)
	)
Exit /B
```

**Comment by brentjohnston** [comment]
Also any luck with the onnx (ort) c# stuff? I tried everything I could in the meshbehavior.cs but it would always still give the rendertexture error. 

This would be so much better than doing these outside scripts we are attemping, to just drag and drop the onnx in the onnx folder for Marigold and depth-anything like the other models.

**Comment by brentjohnston** [comment]
Question for parkchamchi. It seems like the error with the script from is coming from here, I only found this because Unknwon is spelled wrong 
![image](https://github.com/parkchamchi/DepthViewer/assets/23625562/2e2e6a1e-afc8-436a-bdef-dd908f2bbb6b)

the danyrunner.py is indeed present in /depthpy folder. I have tried a fresh beta6 build and it's always the same error, which makes me think maybe threedeejay is using this script on a slightly older build for the script to work?

Here is the error I get when I run the script, I'm so close
![img2](https://github.com/parkchamchi/DepthViewer/assets/23625562/f5ed66a3-88af-4a18-ac37-5704684d578c)

**Comment by brentjohnston** [comment]
Threedeejay sent me a copy of his depthviewer folder and it works. Here is a comparison of the models. I tested with a sort of blurrier image here to see how it would do.

Built-in Model:
![built-in](https://github.com/parkchamchi/DepthViewer/assets/23625562/83ca0344-0952-4979-a588-539a367c3c54)

Beit Model:
![beit](https://github.com/parkchamchi/DepthViewer/assets/23625562/854158f7-ab47-4724-88d6-2fb7a803f088)

Depth-anyone small Model:
![depthanyone-small](https://github.com/parkchamchi/DepthViewer/assets/23625562/c58f8b75-8881-4333-888e-c7b310d0dbfc)

Depth-anyone large Model:
![depthanyone-large](https://github.com/parkchamchi/DepthViewer/assets/23625562/f4910833-596d-44fb-826d-bc2df5cee90d)

Marigold Model:
![marigold](https://github.com/parkchamchi/DepthViewer/assets/23625562/76f0d926-ecdc-4a1a-976e-a30d60990e5c)

Marigold still seems like the best albeit the slowest of the bunch for sure.

**Comment by parkchamchi** [comment]
@brentjohnston Yes, the `dannyrunner.py` commit (fa2ce83) was after `v0.9.1-beta.6` (1fc6b4e), so the existing python scripts could not feed `-r dany`.

**Comment by brentjohnston** [comment]
I'm actually am using `v0.9.1-beta.6` here is a video I've attached of threedeejay's build he just sent me his the scripts inside (first part of video) then I copy his script to fresh build and it gives that error. I keep running into issues that don't make sense :)

https://github.com/parkchamchi/DepthViewer/assets/23625562/69e37eb9-393f-4877-87aa-5242f7555a74

For reference, here is video to show fresh install process and still the error about `Unkwon runner`

https://github.com/parkchamchi/DepthViewer/assets/23625562/9ebab296-d1f3-4e5e-8be9-1d5da40c9a21

I can't find the difference between threedeejay's beta6 and a fresh install, want to fix this so I can build my own modified version again with additional Meta quest 3 features.

**Comment by brentjohnston** [comment]
I think a found the problem, the one from the beta6 release shows Windows (CR LF) format, the one in the working beta6 build from Threedeejay shows Unix (LF) format. If I change one in the release zip to Unix (LF) format and save it it works. The scripts are identical besides that.

![threedeejay-beta6](https://github.com/parkchamchi/DepthViewer/assets/23625562/4cc4b472-d53d-4c2d-a282-4bf42934b164)
![release-build](https://github.com/parkchamchi/DepthViewer/assets/23625562/bd978721-4d83-4dc1-b0c9-fc1dc626b1fc)

**Comment by parkchamchi** [comment]
@brentjohnston I do not believe that the newline has any impact on the code, I wrote about it in (#18).

**Comment by brentjohnston** [comment]
Thank you, yes I got it now and closed the other issue. I even tried some prograns and it said the code was exaclty the same but it lied to me.

**Comment by parkchamchi** [comment]
So I looked into the Depth-Anything. This is the working python script of using dany ORT [#](https://github.com/parkchamchi/DepthViewer/blob/master/DEPTH/depthpy/danyortrunner.py) (activated w/ `-r danyort`) and this is existing MiDaS ORT script [#](https://github.com/parkchamchi/DepthViewer/blob/master/DEPTH/depthpy/ortrunner.py). It appears that there is no difference other than the input/output size is fixed to `518x518`, so I set on the C# ORT side
```csharp
int w = 518;
int h = 518;
//...
return new Depth(output, 518, 518);
```

![image](https://github.com/parkchamchi/DepthViewer/assets/57679724/8b11350a-0eaf-46a9-942c-4144b977c678)

But the output gives me this, whose value is increasing *except* the last pixel. I don't know what causes this.

**Comment by ThreeDeeJay** [comment]
Ayo, been real quiet 'round these parts
Just wanted to give you the heads up: they finally released V2 👀👌 
https://github.com/DepthAnything/Depth-Anything-V2
![teaser](https://github.com/DepthAnything/Depth-Anything-V2/blob/main/assets/teaser.png?raw=true)
ONNX and PT files here but they don't work https://github.com/fabio-sim/Depth-Anything-ONNX/releases/latest

**Comment by ThreeDeeJay** [comment]
Quick update: the "dynamic" variants of Depth Anything V2 added here work with DepthViewer right out of the box
https://github.com/fabio-sim/Depth-Anything-ONNX/releases
GPU usage is high but performance is still not great on my 2080 Ti. Hopefully newer GPUs get closer to realtime.
Also tried using the ONNXRuntime, but then it uses the CPU and performance is awful, and trying to use the CPU fails to load the model.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a8b519a6-7126-44c4-a635-71a28732fdd9" />

I followed the steps [here](https://github.com/parkchamchi/DepthViewer/issues/5#issuecomment-1657791622), but for CUDA 12.9 (13 is apparently not available for Windows?). So I might have to try it again later with CUDA 11.7 which worked in the past.
